import { FaFilePdf, FaLaptop } from 'react-icons/fa6';

import BibtexSection from '@/components/BibtexSection';
import {
  type Project,
  ProjectView,
  Section,
} from '@/components/ProjectComponents';

const project: Project = {
  title: 'Diceplay: A Modular Canvas for Physical Image Composition',
  authors: [
    {
      name: 'Milin Kodnongbua',
      href: 'https://mkodnongbua.com',
      remark: '*,1',
    },
    {
      name: 'Zihan Jack Zhang',
      href: 'https://zzhang-18.github.io/',
      remark: '*,2',
    },
    {
      name: 'Shishi Xiao',
      remark: '*,2',
    },
    {
      name: 'Vivian Li',
      remark: '2',
    },
    {
      name: 'Heather Robertson',
      remark: '2',
    },
    {
      name: 'Rulin Chen',
      remark: '3',
    },
    {
      name: 'David Laidlaw',
      remark: '2',
    },
    {
      name: 'Adriana Schulz',
      href: 'https://www.computationaldesign.group/adriana',
      remark: '2',
    },
  ],
  authorRemarks: {
    '*': 'Equal contribution',
    '1': 'University of Washington',
    '2': 'Brown University',
    '3': 'Beijing Normal-Hong Kong Baptist University',
  },
  venue: 'SIGGRAPH 2026 (Conference Track)',
  links: [
    {
      icon: FaFilePdf,
      label: 'Paper, PDF',
      href: '/assets/papers/SIG-2026-DicePlay.pdf',
    },
    {
      icon: FaLaptop,
      label: 'Interactive UI',
      href: 'https://vli18.github.io/diceplay_ui/',
    },
  ],
  teaser: '/assets/projects/diceplay/2026-diceplay.png',
  teaser_description: `Diceplay, a modular physical canvas for abstract visual composition. Diverse abstract designs automatically generated by our optimization framework
are physically realized using a low-power, LED-enabled dice display, which can be reconfigured through changes in dice orientation and dynamically updated
via programmable color.`,
} as const;

export default function Page() {
  return (
    <ProjectView project={project}>
      <Section title='Abstract'>
        <p>
          We present Diceplay, a modular physical display for abstract visual
          compo sition built from a grid of identical dice. Each die has six
          faces with distinct geometric primitives, and images emerge through
          the placement and orien tation of the dice. While this medium enables
          reusable and reconfigurable physical imagery, it poses a challenging
          design problem: images must be expressed through discrete, extremely
          low-resolution abstractions, making manual authoring difficult. To
          address this challenge, we introduce a compu tational design system
          that automatically generates Diceplay configurations from text
          prompts. Our key technical contribution is a grammar-based for
          mulation that relaxes this discrete design space into a smooth
          optimization landscape, enabling gradient-based optimization using
          score distillation sampling. We show that our approach consistently
          produces meaningful abstractions for this medium, whereas
          state-of-the-art smoothing techniques fail in this extremely
          challenging regime. We demonstrate our method across a range of
          prompts and fabricated examples, showing how computationally generated
          abstractions can be realized as physical visual artifacts.
        </p>
      </Section>
      <Section title='Fast Forward'>
        <div className='rounded-md shadow-small p-2 mt-4 bg-white'>
          <video
            width='1080'
            height='360'
            loop
            autoPlay
            playsInline
            muted
            src='/assets/projects/diceplay/ff.mp4'
          />
        </div>
      </Section>
      <Section title='Demo'>
        <div className='rounded-md shadow-small p-2 mt-4 bg-white'>
          <video
            width='1080'
            height='360'
            controls
            autoPlay
            muted
            playsInline
            src='/assets/projects/diceplay/supplemental-vid.mp4'
          />
        </div>
      </Section>
      <BibtexSection>
        {`@inproceedings{kodnongbua2026diceplay,
  author    = {Kodnongbua, Milin and Zhang, Zihan and Xiao, Shishi and Li, Vivian and Robertson, Heather and Chen, Rulin and Laidlaw, David and Schulz, Adriana},
  title     = {Diceplay: A Modular Canvas for Physical Image Composition},
  year      = {2026},
  publisher = {Association for Computing Machinery},
  address   = {New York, NY, USA},
  abstract  = {We present Diceplay, a modular physical display for abstract visual composition built from a grid of identical dice. Each die has six faces with distinct geometric primitives, and images emerge through the placement and orientation of the dice. While this medium enables reusable and reconfigurable physical imagery, it poses a challenging design problem: images must be expressed through discrete, extremely low-resolution abstractions, making manual authoring difficult. To address this challenge, we introduce a computational design system that automatically generates Diceplay configurations from text prompts. Our key technical contribution is a grammar-based formulation that relaxes this discrete design space into a smooth optimization landscape, enabling gradient-based optimization using score distillation sampling. We show that our approach consistently produces meaningful abstractions for this medium, whereas state-of-the-art smoothing techniques fail in this extremely challenging regime. We demonstrate our method across a range of prompts and fabricated examples, showing how computationally generated abstractions can be realized as physical visual artifacts.},
  booktitle = {SIGGRAPH 2026 Conference Papers},
  numpages  = {11},
  location  = {Los Angeles, CA, USA},
  keywords  = {optimization, fabrication, shape grammar},
  preview   = {2026-diceplay.png},
  html      = {/publications/diceplay},
  pdf       = {/assets/papers/SIG-2026-DicePlay.pdf}
}
`}
      </BibtexSection>
    </ProjectView>
  );
}
